name: GitHub Workflow - Database Script

on:
  workflow_call:
  
jobs:
  run-in-pull-request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run a one-line script
        run: echo "Executado script do liquibase no pull request"
